import Layout from '@/components/Layout'
import SideBar from '@/components/SideBar'
import Head from 'next/head'
import prisma from '../../lib/prisma';

export default function Home({movies}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className='grid grid-cols-12 gap-4'>
          <aside className='col-span-3 h-screen bg-teal-800'>
            <SideBar/>
          </aside>
          <section className='col-start-4 col-end-13'>
            <div>
              {movies.map((movie) => {
                return <p key={movie.MoviesID}>{movie.M_title}</p>
              })}
            </div>
          </section>
        </main>
      </Layout>
    </>
  )
}

export async function getServerSideProps()
{
  const movies = await prisma.movies.findMany({
    where: {
      MoviesID: {lte: 10}
    }
  });
  console.log(JSON.parse(JSON.stringify(movies)));

  return {
    props: { 
      movies: JSON.parse(JSON.stringify(movies)), 
    }
  }
}