import { useSession } from 'next-auth/react';
import { useState } from "react"

import Layout from '@/components/Layout'
import MovieDisplay from '@/components/MovieDisplay';
import Head from 'next/head'

export default function Search() {
  const { data : session } = useSession();

  //form data
  const [title, setTitle] = useState("");
  const [year, setYear] = useState("");
  const [genre, setGenre] = useState("");
  const [rating, setRating] = useState(1.0);

  //page changing props
  const [movies, setMovies] = useState([]);
  const [movieCount, setMovieCount] = useState(0);
  const [page, setPage] = useState(1);

  //API route req handler
  async function handleSubmit(e)
  {
    e.preventDefault();
    setPage(1)
    const response = await fetch(`/api/get-movies`, {
      method: "POST",
      body: JSON.stringify({ title, year, rating, genre }),
      headers: {
        "Content-Type": "application/json",
      }
    })

    const { movies, movieCount } = await response.json();

    setMovieCount(movieCount);
    setMovies(movies);
  }

  //prev page
  function handlePrev()
  {
    setPage(prevPage => Math.max(prevPage - 1, 1));
  }

  //next page
  function handleNext()
  {
    setPage(prevPage => prevPage + 1)
  }

  console.log(page);

  if (session) {
    return (
      <>
        <Head>
          <title>Bulls Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <main className='grid grid-cols-12 gap-4 min-h-screen'>
            <aside className='col-span-3 xl:col-span-2 h-full bg-teal-800'>
            <div className="w-11/12 mx-auto mt-8 text-white">
              <form 
                  onSubmit={handleSubmit}
                  className="flex flex-col rounded-md px-5 py-5 m-auto"
              > 
                <h2 className="text-4xl my-3">Search</h2>

                
                <label htmlFor="title" className="mt-1 text-white">Title</label>
                <input 
                  value={title} onChange={(e) => setTitle(e.target.value)}
                  type="text" 
                  id="title" 
                  placeholder="Title" 
                  className="bg-transparent text-white border-b-4 my-1 p-3 rounded-sm hover:border-green-600 hover:cursor-pointer"
                />

                <label htmlFor="year" className="mt-1 ">Year</label>
                <input
                  value={year}
                  onChange={(e) => setYear(e.target.value)}
                  type="text"
                  id="year"
                  placeholder="Year"
                  className="my-1 bg-transparent hover:cursor-pointer border-b-4 p-3 rounded-sm hover:border-green-600"
                />

                <label htmlFor="genre" className="mt-1 ">Genre</label>
                <select
                  value={genre}
                  onChange={(e) => setGenre(e.target.value)}
                  id="genre"
                  
                  className="my-1 bg-transparent hover:cursor-pointer border-b-4 p-3 rounded-sm hover:border-green-600"
                >
                  <option value="">--Select--</option>
                  <option value="Action">Action</option>
                  <option value="Adventure">Adventure</option>
                  <option value="Animation">Animation</option>
                  <option value="Comedy">Comedy</option>
                  <option value="Drama">Drama</option>
                  <option value="Family">Family</option>
                  <option value="Mystery">Mystery</option>
                  <option value="Thriller">Thriller</option>
                  <option value="War">War</option>
                </select>

                <label className="mt-1" htmlFor="rating">Rating &gt;= {rating}</label>
                <input
                  className='my-3'
                  id='rating'
                  type="range"
                  min="1.0"
                  max="10.0"
                  step="0.1"
                  value={rating}
                  onChange={(e) => setRating(parseFloat(e.target.value))}
                />

                <button type='submit' className="my-3 p-3 hover:bg-green-600 bg-green-500 border-2 rounded-md">Search</button>
              </form>
            </div>
            </aside>
            <section className='w-10/12 h-full m-auto col-start-4 xl:col-start-3 col-end-13'>
              {movies.length > 0 && <p className='my-4 font-bold text-gray-500'>{(page - 1) * 12} - {page * 12} of the {movieCount} movies found</p>}
              <MovieDisplay 
                movies={movies}
                session={session}
                page={page}
              />
              <div className='p-4 flex justify-around items-center'>
                <button 
                  style={page <= 1 || movies.length == 0 ? {opacity: 0, pointerEvents: "none"} : {opacity: 1}}
                  className="py-3 px-5 border border-1 hover:bg-teal-900/50 border-teal-900 rounded-xl"
                  onClick={handlePrev}
                >
                    &larr; Prev
                </button>
                <button
                  style={page * 12 < movieCount ? {opacity: 1} : {opacity: 0, pointerEvents: "none"}}
                  className="py-3 px-5 border border-1 hover:bg-teal-900/50 border-teal-900 rounded-xl"
                  onClick={handleNext}>
                    Next &rarr;
                </button>
              </div>
            </section>
          </main>
        </Layout>
      </>
    )
  }
  else 
  {
    return <p>No user signed in</p>
  }
}